//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anexos()
        {
            this.AnexosPlantacion = new HashSet<AnexosPlantacion>();
        }
    
        public short Id { get; set; }
        public byte Secuencia { get; set; }
        public string Descripcion { get; set; }
        public bool EsObligatorio { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> RegistroPlantacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnexosPlantacion> AnexosPlantacion { get; set; }
    }
}
