//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact_PlantacionesProduccion
    {
        public string ARFFS { get; set; }
        public string SEDE { get; set; }
        public string Estado { get; set; }
        public string Ubigeo { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Zona { get; set; }
        public string SistemaPlantacion { get; set; }
        public string Finalidad { get; set; }
        public short AnioPlantacion { get; set; }
        public byte MesPlantacion { get; set; }
        public string NombreEspecie { get; set; }
        public string NombreComun { get; set; }
        public string Tipo_Plantacion { get; set; }
        public Nullable<int> NroPlantado { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<decimal> ProduccionEstimada { get; set; }
    }
}
