//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantacionDetalleVertices
    {
        public decimal Id { get; set; }
        public decimal PlantacionDetalle_Id { get; set; }
        public int NumeroSecuencia { get; set; }
        public string CoordenadaEsteUTM { get; set; }
        public string CoordenadaNorteUTM { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual PlantacionDetalle PlantacionDetalle { get; set; }
    }
}
