//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantacionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantacionDetalle()
        {
            this.PlantacionDetalleEspecie = new HashSet<PlantacionDetalleEspecie>();
            this.PlantacionDetalleVertices = new HashSet<PlantacionDetalleVertices>();
        }
    
        public decimal Id { get; set; }
        public int Plantacion_Id { get; set; }
        public byte SistemaPlantacion_Id { get; set; }
        public Nullable<byte> Finalidad_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> AreaPredio { get; set; }
        public Nullable<byte> MesEstablecimiento { get; set; }
        public Nullable<short> AnnioEstablecimiento { get; set; }
        public Nullable<decimal> CantidadSuperficieHa { get; set; }
        public Nullable<decimal> CantidadSuperficieMl { get; set; }
        public string CoordenadaEsteUTM { get; set; }
        public string CoordenadaNorteUTM { get; set; }
        public string UriStorageFileName { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<int> SistemaCoordenada_Id { get; set; }
    
        public virtual SistemaCoordenada SistemaCoordenada { get; set; }
        public virtual FinalidadProducto FinalidadProducto { get; set; }
        public virtual Plantacion Plantacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantacionDetalleEspecie> PlantacionDetalleEspecie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantacionDetalleVertices> PlantacionDetalleVertices { get; set; }
        public virtual SistemaPlantacion SistemaPlantacion { get; set; }
    }
}
