//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantacion()
        {
            this.AnexosPlantacion = new HashSet<AnexosPlantacion>();
            this.PersonaPlantacion = new HashSet<PersonaPlantacion>();
            this.PlantacionHistorico = new HashSet<PlantacionHistorico>();
            this.RevisionesRegistroPlantaciones = new HashSet<RevisionesRegistroPlantaciones>();
            this.PlantacionDetalle = new HashSet<PlantacionDetalle>();
        }
    
        public int Id { get; set; }
        public string NumeroCertificado { get; set; }
        public string NombrePredio { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Zona { get; set; }
        public string Datum { get; set; }
        public string CoordenadaNorteUTM { get; set; }
        public string CoordenadaEsteUTM { get; set; }
        public Nullable<short> Ubigeo_Id { get; set; }
        public Nullable<byte> TipoZona_Id { get; set; }
        public string NombreZona { get; set; }
        public bool EsPropietario { get; set; }
        public string DocumentoCondicion { get; set; }
        public Nullable<byte> TipoAutorizacion_Id { get; set; }
        public string DocumentoContrato { get; set; }
        public Nullable<System.DateTime> FechaRecepcionARFFS { get; set; }
        public bool AprobadoEspecialista { get; set; }
        public bool AprobadoDIR { get; set; }
        public bool AprobadoCatastro { get; set; }
        public Nullable<decimal> CantidadTotalSuperficieMl { get; set; }
        public Nullable<decimal> CantidadTotalSuperficieHa { get; set; }
        public string Observaciones { get; set; }
        public byte SeccionAvance { get; set; }
        public Nullable<short> Sede_Id { get; set; }
        public Nullable<short> SedePrincipal_Id { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<byte> TipoComunidad_Id { get; set; }
        public bool EsPosesionario { get; set; }
        public bool EsInversionista { get; set; }
        public string Estado { get; set; }
        public string LocalKey { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; } //TYLER 20/11/19 FECHA FIRMA
        public string ObjectId { get; set; } //TYLER 20/11/19 FECHA FIRMA
        public string EstadoGeo { get; set; } //TYLER 20/11/19 FECHA FIRMA
        public string NumeroPredio { get; set; } //TYLER 20/11/19 FECHA FIRMA
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnexosPlantacion> AnexosPlantacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPlantacion> PersonaPlantacion { get; set; }
        public virtual TipoAutorizacion TipoAutorizacion { get; set; }
        public virtual TipoComunidad TipoComunidad { get; set; }
        public virtual TipoZona TipoZona { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantacionHistorico> PlantacionHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionesRegistroPlantaciones> RevisionesRegistroPlantaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantacionDetalle> PlantacionDetalle { get; set; }
        public virtual SedeAutoridadForestal SedeAutoridadForestal { get; set; }
        public virtual SistemaCoordenada SistemaCoordenada { get; set; }
        public int? SistemaCoordenada_Id { get; internal set; }
    }
}
