//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinonimo
    {
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public int Especie_Id { get; set; }
        public string Fuente { get; set; }
    
        public virtual Especie Especie { get; set; }
    }
}
