//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.GeneralCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoDerechoSemilla
    {
        public int Id { get; set; }
        public Nullable<byte> ATFFS_Id { get; set; }
        public Nullable<short> Annio { get; set; }
        public Nullable<short> Correlativo { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual AutoridadForestal AutoridadForestal { get; set; }
    }
}
