//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.GeneralCore.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneralSchema : DbContext
    {
        public GeneralSchema()
            : base("name=GeneralSchema")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directorio> Directorio { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoAutorizacion> TipoAutorizacion { get; set; }
        public virtual DbSet<TipoComunidad> TipoComunidad { get; set; }
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<SedeAutoridadForestal> SedeAutoridadForestal { get; set; }
        public virtual DbSet<TipoSede> TipoSede { get; set; }
        public virtual DbSet<CodigoDerechoSemilla> CodigoDerechoSemilla { get; set; }
        public virtual DbSet<SistemaPlantacion> SistemaPlantacion { get; set; }
        public virtual DbSet<TipoFinalidad> TipoFinalidad { get; set; }
        public virtual DbSet<TipoPlantacion> TipoPlantacion { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<Sinonimo> Sinonimo { get; set; }
        public virtual DbSet<TipoZona> TipoZona { get; set; }
        public virtual DbSet<AutoridadForestal> AutoridadForestal { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
    }
}
