//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.GeneralCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMedida
    {
        public byte Id { get; set; }
        public string Simbolo { get; set; }
        public string Descripcion { get; set; }
    }
}
