//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexosPlantacion
    {
        public decimal Id { get; set; }
        public int Plantacion_Id { get; set; }
        public short Anexo_Id { get; set; }
        public byte Secuencia { get; set; }
        public string UriStorageFileName { get; set; }
        public Nullable<long> Tamanio { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Anexos Anexos { get; set; }
        public virtual Plantacion Plantacion { get; set; }
    }
}
