//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.InventarioCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brigadista
    {
        public int Id { get; set; }
        public int IdInventario { get; set; }
        public int IdPersona { get; set; }
        public Nullable<int> IdTipoRolBrigada { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual TipoRolBrigada TipoRolBrigada { get; set; }
    }
}
