//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.InventarioCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conduccion()
        {
            this.InventarioUM = new HashSet<InventarioUM>();
        }
    
        public int Id { get; set; }
        public int IdPredio { get; set; }
        public int IdPersona { get; set; }
        public int IdTipoConductor { get; set; }
        public int IdUnidadMuestreo { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Predio Predio { get; set; }
        public virtual TipoConductor TipoConductor { get; set; }
        public virtual UnidadMuestreo UnidadMuestreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioUM> InventarioUM { get; set; }
    }
}
