//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteresadoDetalle
    {
        public decimal Id { get; set; }
        public Nullable<int> Interesado_Id { get; set; }
        public byte SistemaPlantacion_Id { get; set; }
        public Nullable<short> Especie_Id { get; set; }
        public string NombreComun { get; set; }
        public Nullable<byte> Finalidad_Id { get; set; }
        public byte UnidadMedida_Id { get; set; }
        public Nullable<decimal> PlantacionEstimada { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual EspecieForestal EspecieForestal { get; set; }
        public virtual FinalidadProducto FinalidadProducto { get; set; }
        public virtual Interesado Interesado { get; set; }
        public virtual SistemaPlantacion SistemaPlantacion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
