//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.InventarioCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioEspecie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioEspecie()
        {
            this.InventarioArbol = new HashSet<InventarioArbol>();
        }
    
        public int Id { get; set; }
        public int IdInventarioUM { get; set; }
        public short IdEspecieForestal { get; set; }
        public int IdTipoUso { get; set; }
    
        public virtual EspecieForestal EspecieForestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioArbol> InventarioArbol { get; set; }
        public virtual InventarioUM InventarioUM { get; set; }
        public virtual TipoUso TipoUso { get; set; }
    }
}
