//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.InventarioCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCentral
    {
        public int Id { get; set; }
        public int IdUnidadMuestreo { get; set; }
        public System.DateTime FechaInstMarca { get; set; }
        public string HoraInstMarca { get; set; }
        public string CodigoGPS { get; set; }
        public byte IdTipoZona { get; set; }
        public decimal CoordenadaUTMX { get; set; }
        public decimal CoordenadaUTMY { get; set; }
        public Nullable<decimal> ErrorGPS { get; set; }
        public Nullable<decimal> Altitud { get; set; }
    
        public virtual TipoZona TipoZona { get; set; }
        public virtual UnidadMuestreo UnidadMuestreo { get; set; }
    }
}
