//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionesRegistroPlantaciones
    {
        public int Id { get; set; }
        public int Plantacion_Id { get; set; }
        public string Descripcion { get; set; }
        public bool EsAprobado { get; set; }
        public string Rol { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Plantacion Plantacion { get; set; }
    }
}
