//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.PlantacionCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemaCoordenada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SistemaCoordenada()
        {
            this.PlantacionDetalle = new HashSet<PlantacionDetalle>();
        }
    
        public int id { get; set; }
        public string Zona { get; set; }
        public string Datum { get; set; }
        public decimal LatitudMin { get; set; }
        public decimal LatitudMax { get; set; }
        public decimal LongitudMin { get; set; }
        public decimal LongitudMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantacionDetalle> PlantacionDetalle { get; set; }
    }
}
