//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.ListasExcelCore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excel_LicenciasCazaDeportiva
    {
        public short Id { get; set; }
        public string AutoridadForestal { get; set; }
        public string Numero { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string CausalesExtinsion { get; set; }
        public string NumeroResolucion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
    }
}
