//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERFOR.Component.SeguridadCore.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecuritySchema : DbContext
    {
        public SecuritySchema()
            : base("name=SecuritySchema")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoridadForestal> AutoridadForestal { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Directorio> Directorio { get; set; }
        public virtual DbSet<SedeAutoridadForestal> SedeAutoridadForestal { get; set; }
        public virtual DbSet<TipoSede> TipoSede { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<MiembroRol> MiembroRol { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
    }
}
